steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run unit tests
#  - name: python
#    entrypoint: python
#    args: ["-m", "pylint", "app.py"]

  # Run code analyzer
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "tests/unit/unit_tests.py", "--junitxml=${SHORT_SHA}_test_log.xml"]

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'jenkins-monitor-service',
           '--image=gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA',
           '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated',
           '--set-env-vars', 'JENKINS_MONITOR_BASE_POSTGRES_PORT=5432,',
           'JENKINS_MONITOR_BASE_POSTGRES_USERNAME=postgres,',
           'JENKINS_MONITOR_BASE_POSTGRES_ADDRESS=$$DB_ADDRESS_SECRET,',
           'JENKINS_MONITOR_BASE_POSTGRES_PASSWORD=$$DB_PASSWORD_SECRET,',
           'JENKINS_MONITOR_MDA_POSTGRES_DATABASE=postgres,',
           'JENKINS_MONITOR_MDA_JENKINS_USERNAME=$$MDA_USERNAME_SECRET,',
           'JENKINS_MONITOR_MDA_JENKINS_PASSWORD=$$MDA_PASSWORD_SECRET,',
           'JENKINS_MONITOR_MDA_JENKINS_URL=$$MDA_URL_SECRET']
    secretEnv: ['DB_ADDRESS_SECRET', 'DB_PASSWORD_SECRET', 'MDA_USERNAME_SECRET', 'MDA_PASSWORD_SECRET', 'MDA_URL_SECRET']

images:
  - gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA

availableSecrets:
  secretManager:
  - versionName: projects/846630294631/secrets/DB_ADDRESS_SECRET/versions/latest
    env: 'DB_ADDRESS_SECRET'
  - versionName: projects/846630294631/secrets/DB_PASSWORD_SECRET/versions/latest
    env: 'DB_PASSWORD_SECRET'
  - versionName: projects/846630294631/secrets/MDA_USERNAME_SECRET/versions/latest
    env: 'MDA_USERNAME_SECRET'
  - versionName: projects/846630294631/secrets/MDA_PASSWORD_SECRET/versions/latest
    env: 'MDA_PASSWORD_SECRET'
  - versionName: projects/846630294631/secrets/MDA_URL_SECRET/versions/latest
    env: 'MDA_URL_SECRET'