steps:
  - name: 'export'
    args: ['PROJECT_ID="$(gcloud config get-value project -q)']
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run unit tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "tests/unit/unit_tests.py", "--junitxml=${SHORT_SHA}_test_log.xml"]
#gcr.io/esoteric-bruin-312613/jenkins-monitor-docker
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/$PROJECT_ID/$_REPO_NAME/jenkins-monitor-docker:$SHORT_SHA', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/$PROJECT_ID/$_REPO_NAME/jenkins-monitor-docker:$SHORT_SHA']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'helloworld',
           '--image=gcr.io/$PROJECT_ID/$_REPO_NAME/jenkins-monitor-docker:$SHORT_SHA',
           '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated']

# Save test logs to Google Cloud Storage
#artifacts:
#  objects:
#    location: gs://$_BUCKET_NAME/
#    paths:
#      - ${SHORT_SHA}_test_log.xml
# Store images in Google Artifact Registry
images:
  - gcr.io/$PROJECT_ID/$_REPO_NAME/jenkins-monitor-docker:$SHORT_SHA