steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run unit tests
  - name: python
    entrypoint: python
    args: ["-m", "pylint", "app.py"]

  # Run code analyzer
#  - name: python
#    entrypoint: python
#    args: ["-m", "pytest", "tests/unit/unit_tests.py", "--junitxml=${SHORT_SHA}_test_log.xml"]

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'jenkins-monitor-service',
           '--image=gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA',
           '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated']
    env:
      - 'JENKINS_MONITOR_POSTGRES_PORT=PORT'
      - 'JENKINS_MONITOR_POSTGRES_ADDRESS=ADDRESS'

images:
  - gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA