steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run unit tests
#  - name: python
#    entrypoint: python
#    args: ["-m", "pylint", "app.py"]

  # Run code analyzer
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "tests/unit/unit_tests.py", "--junitxml=${SHORT_SHA}_test_log.xml"]

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'jenkins-monitor-service',
           '--image=gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA',
           '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated',
           '--set-env-vars', 'JENKINS_MONITOR_BASE_POSTGRES_PORT=5432',
           '--set-env-vars', 'JENKINS_MONITOR_BASE_POSTGRES_ADDRESS=ADDRESS_SECRET',
           '--set-env-vars', 'JENKINS_MONITOR_BASE_POSTGRES_USERNAME=USERNAME_DB_SECRET',
           '--set-env-vars', 'JENKINS_MONITOR_BASE_POSTGRES_PASSWORD=PASSWORD_DB_SECRET',
           '--set-env-vars', 'JENKINS_MONITOR_MDA_POSTGRES_DATABASE=MDA_DATABASE',
           '--set-env-vars', 'JENKINS_MONITOR_MDA_JENKINS_USERNAME=USERNAME_MDA_SECRET',
           '--set-env-vars', 'JENKINS_MONITOR_MDA_JENKINS_PASSWORD=PASSWORD_MDA_SECRET',
           '--set-env-vars', 'JENKINS_MONITOR_MDA_JENKINS_URL=URL_MDA_SECRET']

images:
  - gcr.io/$PROJECT_ID/jenkins-monitor-docker:$SHORT_SHA